### ISSUE TITLE
visualizations.raster improvements

### ISSUE THREAD

**Issue by lmcintosh** [baccuslab/pyret#54]
Would be nice if this were simpler; i.e. just take an (n,2) array of spike times and cell / trial ID

**Comment by leongjcs** [comment]
I agree.

**Comment by nirum** [comment]
we should split the current code in `visualizations.raster` into two functions, one that splits a list of spike times into multiple trials given a trial length, and then the `raster` function should just take something like a two-column ndarray where the first is the spike times and the second is a label or index for that spike time.

e.g.:

```python
raster(spk_array):
   plt.plot(spk_array[:,0], spk_array[:,1], '.');
```

This lets you use `raster` if you want to plot a raster across cells instead of trials, for example.

**Comment by nirum** [comment]
Thoughts, @bnaecker? This is a breaking change, but makes things simpler. Check out the modifications in the above commit
